export * from "./Input";
export * from "./CustomSelect";
export * from "./Table";
export * from "./Button";
export * from "./Loader";
export * from "./Colors";
export * from "./Text";
export * from "./Burger";
export * from "./Pagination-old";
