const loginRes = {
  exception: null,
  responseCode: "00",
  responseMessage: "Success",
  status: true,
  statusCode: 200,
  data: {
    personFirstName: "Chijioke",
    personFullName: "Chijioke Ofoma",
    personDistinguishedName:
      "CN=Chijioke Ofoma,OU=BOI Users,OU=BOI Managed Structure,DC=boi,DC=ng",
    personSurname: "Ofoma",
    personJobTitle: "TEAM MEMBER",
    personJobDescription: null,
    personUserPrincipalName: "COfoma@boi.ng",
    personMobileNumber: "07036280310",
    personEmail: "COfoma@boi.ng",
    personEmployeeID: "1000",
    personStaffRole: "Internal Control",
    persongrade: "Senior Banking Officer",
    personDepartment: "OPERATIONAL EXCELLENCE (SYNERGY)",
    personDisplayname: "Chijioke V. Ofoma",
    personDescription: "BOI Staff",
    personSAMAccountName: "COfoma",
    personCompany: "BANK OF INDUSTRY",
    personManager:
      "CN=Olatunji Akanbi,OU=BOI Users,OU=BOI Managed Structure,DC=boi,DC=ng",
    personmemberof: [
      "BOI BPM Administrators",
      "BOI SSL VPN",
      "BOI-Desktop-Support",
      "BOI Desktop Support",
      "opexcellencegroup",
      "STAFF",
    ],
    personAddress1: null,
    personLocation: null,
    personCountryCode: "0",
    personHomePhone: null,
    personIpPhone: null,
    personCountry: null,
    personMiddlename: null,
    personimage: null,
    persongender: null,
    persondateofbirth: null,
    personmaritalstatus: null,
  },
};

export { loginRes };
